Serilog:
  MinimumLevel:
    Default: 'Debug'
    Override:
      System.Net.Http.HttpClient: 'Information'
      Microsoft.EntityFrameworkCore.Database.Command: 'Information'

Application:
  EnableSwagger: true

ConnectionStrings:
  Database: "Host=localhost;Port=51946;Database=goblin;Username=postgres;Password=postgres;Pooling=true;GSS Encryption Mode=Disable"

