trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'installing dotnet'
  inputs:
    version: '2.2.103'
- script: dotnet restore
  workingDirectory: "src/"
  displayName: 'restoring packages'
- task: DotNetCoreCLI@2
  displayName: 'building projects'
  inputs:
    command: build
    projects: '*src/**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'running tests'
  inputs:
    command: test
    projects: 'src/**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'